### PR TITLE
fix crs error

### PR DESCRIPTION
**Pull request by limnoliver**

### CODE REVIEW

**Comment by wdwatkins** [comment]
Hmm, the projection of the boundary didn't change did it?  This change makes sense, but this should have error locally if 102039 was the wrong CRS.

**Comment by limnoliver** [comment]
Yes, I'm confused by why my change worked.

**Comment by wdwatkins** [comment]
Was the error a CRS mismatch between the dams/reservoirs and the boundary?

**Comment by limnoliver** [comment]
No, in both the dams and reservoirs cases, I got this error: https://github.com/USGS-R/delaware-model-prep/pull/36#discussion_r423022643

**Pull request merged**
